easy_admin:
      site_name: 'DASHBOARD <em style="font-size:60%">WebMagAgency</em>'
      list:
        title: 'list.%%entity_label%%'
        actions:
            - { name: 'show', icon: 'search' }
            - { name: 'edit',, icon: 'edit' }
            - { name: 'delete', icon: 'trash' }
      show:
          title: '%%entity_name%% (#%%entity_id%%)'
      formats:
          datetime: 'd/m/Y h:i A'
      design:
          form_theme:
            - "@EasyAdmin/form/bootstrap_4.html.twig"
            - "@FOSCKEditor/Form/ckeditor_widget.html.twig"